{% set name = "MyProxyClient" %}
{% set version = "2.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "0a309413dddff370f4bfc4ad30030575a4be0846afd464cf61f8164942c77241" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - myproxyclient = myproxy.script:main
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pyopenssl

test:
  imports:
    - myproxy
    - myproxy.test
    - myproxy.utils
  commands:
    - myproxyclient --help

about:
  home: "https://github.com/cedadev/MyProxyClient"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "myproxy/LICENSE"
  summary: 'MyProxy Client'

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
