{% set name = "MyProxyClient" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e998f1cf2246abdd1fbeba067f87d00d7a18d3bc138334dd93ae9a5f5ae3e5e

build:
  noarch: python
  number: 0
  entry_points:
    - myproxyclient = myproxy.client.script:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - pip
    - pyopenssl
    - python >=3.6
    - six
    - pytest-runner
    - setuptools_scm
  run:
    - pip
    - pyopenssl
    - pytest
    - python >=3.6
    - six
    - setuptools

test:
  imports:
    - myproxy
    - myproxy.client
    - myproxy.client.test
    - myproxy.client.utils
  commands:
    - myproxyclient --help
    - pytest tests/unit/test_simple.py

about:
  home: "https://github.com/cedadev/MyProxyClient"
  license: BSD-3-Clause
  license_family: BSD
  license_file: myproxy/client/LICENSE
  summary: "Python client implementation of MyProxy credential management service"
  doc_url: https://github.com/cedadev/MyProxyClient#readme
  dev_url: https://github.com/cedadev/MyProxyClient
  description: |
    This a pure Python implementation of a client to the MyProxy Credential
    Management Server (http://grid.ncsa.uiuc.edu/myproxy/).
    It provides both a Python API and a command line interface.
extra:
  recipe-maintainers:
    - valeriupredoi
    - agoodm
    - jarifibrahim
    - cofinoa
