{% set name = "MyProxyClient" %}
{% set version = "2.0.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "5f031e9265b2af7f33c2f2a3ef9844fd6c94812a3f796e06f2b0939a3d00ac4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - myproxyclient = myproxy.script:main
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyopenssl

test:
  imports:
    - myproxy
    - myproxy.test
    - myproxy.utils
  commands:
    - myproxyclient --help

about:
  home: https://github.com/cedadev/MyProxyClient
  license: BSD 3-clause
  license_file: myproxy/LICENSE
  summary: 'MyProxy Client'

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
