appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: WINWUgw7mBYAi8hQUM8lRKuU2ELhn4iMO6J2y200cej3FuEWzFd4JgljBiX1B3fxdEU2xJF+8GQQWtQWvoMJ2G8f2hQlFRCBtx3dYQpxBpBQKm62Sy9C5sguYDsSZvVq5BfdwxYKvwTSI3Wx2VXE+LGatrnsPfEeuSuUqautfWyYCc4NBd16pd8gsjJWYaIxdndKTsq8DASiAqXKaOW730sC5BrALttobWoVuYmGQt0Dj5lAczzDcg3wOCR0fms2GguRdMU62539EEHvHWWzRs5zXLaxSbfgcGxL+q4Q0L8pffiw5I+mg75w3DVnNbsQ3MjEMHgRcXwpznqPDEPXF2QDa0iEEtbDe3YqLqDqWRI3JwjL0YyT1taPHScW73/xwU30pQ35ZME0XMH1WzkSyVJ1s0ehqSXpTXOyVVJTc9bIpSRY2b/JIFGe9igBO4UpaVXzFoIjYe0GFNb3tJaW1O0ktinbFzryAIXpWMvjbHbh13yzR7tJtVZS3Kqhbb4jMWesKNl3qlXyeUpYcW0bfOFkLXvGHQoVB7KAjaWYzrwoPBEmuPmKunAoUsLHyQmbX+jbblEoYnlcMscIZjn1ndbktp0SbgD6bjhs/mne37GdW9ZNyU9k2ClyRSt0HLx4l/DT8OG8/oaThtwj5C3DBoBcoEae8X4PJB1VSlzSMAc=}
